defaults:
  - _self_
  - data: default # choose datamodule with `test_dataloader()` for evaluation
  - model: default
  - loggers: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]
ckpt_path: ???
